services:
  web-app:
    container_name: node
    image: ts-node-web
    environment:
      - MONGODB_URL=mongodb://mongo_db:27017/
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: mongo_db
    image: mongo
    ports:
      - 27017:27017